"""enforce one open return session per user

Revision ID: 1562e08ca875
Revises: 7ef98cb4e30a
Create Date: 2026-07-11 23:55:31.156177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1562e08ca875'
down_revision: Union[str, Sequence[str], None] = '7ef98cb4e30a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_return_sessions_user_open', 'return_sessions', ['user_id'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_return_sessions_user_open', table_name='return_sessions', postgresql_where=sa.text("status = 'OPEN'"))
    # ### end Alembic commands ###
