"""create initial database schema

Revision ID: 7ef98cb4e30a
Revises: 
Create Date: 2026-07-10 19:35:08.659054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ef98cb4e30a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hubs',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'NEAR_FULL', 'FULL', 'MAINTENANCE', 'OFFLINE', name='hub_status_enum'), server_default='ACTIVE', nullable=False),
    sa.Column('pet_capacity', sa.Integer(), server_default='50', nullable=False),
    sa.Column('hdpe_capacity', sa.Integer(), server_default='30', nullable=False),
    sa.Column('pet_current', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hdpe_current', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pickup_threshold_percent', sa.Integer(), server_default='80', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hdpe_capacity > 0', name='ck_hubs_hdpe_capacity_positive'),
    sa.CheckConstraint('hdpe_current >= 0 AND hdpe_current <= hdpe_capacity', name='ck_hubs_hdpe_current_valid'),
    sa.CheckConstraint('pet_capacity > 0', name='ck_hubs_pet_capacity_positive'),
    sa.CheckConstraint('pet_current >= 0 AND pet_current <= pet_capacity', name='ck_hubs_pet_current_valid'),
    sa.CheckConstraint('pickup_threshold_percent BETWEEN 1 AND 100', name='ck_hubs_pickup_threshold_valid'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hubs')),
    sa.UniqueConstraint('code', name=op.f('uq_hubs_code'))
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('student_code', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'DRIVER', name='user_role_enum'), server_default='USER', nullable=False),
    sa.Column('points_balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_bottles_returned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone')),
    sa.UniqueConstraint('student_code', name=op.f('uq_users_student_code'))
    )
    op.create_table('vouchers',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('partner_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('required_points', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.String(length=100), nullable=False),
    sa.Column('quantity_available', sa.Integer(), server_default='100', nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='voucher_status_enum'), server_default='ACTIVE', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expires_at IS NULL OR valid_from IS NULL OR expires_at > valid_from', name='ck_vouchers_valid_period'),
    sa.CheckConstraint('quantity_available >= 0', name='ck_vouchers_quantity_available_non_negative'),
    sa.CheckConstraint('required_points > 0', name='ck_vouchers_required_points_positive'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vouchers')),
    sa.UniqueConstraint('code', name=op.f('uq_vouchers_code'))
    )
    op.create_index('ix_vouchers_status', 'vouchers', ['status'], unique=False)
    op.create_table('pickups',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('hub_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='pickup_status_enum'), server_default='PLANNED', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_batches', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_bottles', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estimated_weight_kg', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at', name='ck_pickups_completion_time_valid'),
    sa.CheckConstraint('estimated_weight_kg >= 0', name='ck_pickups_estimated_weight_non_negative'),
    sa.CheckConstraint('total_batches >= 0', name='ck_pickups_total_batches_non_negative'),
    sa.CheckConstraint('total_bottles >= 0', name='ck_pickups_total_bottles_non_negative'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], name=op.f('fk_pickups_driver_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.id'], name=op.f('fk_pickups_hub_id_hubs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pickups')),
    sa.UniqueConstraint('code', name=op.f('uq_pickups_code'))
    )
    op.create_index(op.f('ix_pickups_driver_id'), 'pickups', ['driver_id'], unique=False)
    op.create_index(op.f('ix_pickups_hub_id'), 'pickups', ['hub_id'], unique=False)
    op.create_table('point_ledger',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('BOTTLE_RETURN', 'BONUS', 'VOUCHER_REDEMPTION', 'MANUAL_ADJUSTMENT', name='point_source_type_enum'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('points_change', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('balance_after >= 0', name='ck_point_ledger_balance_after_non_negative'),
    sa.CheckConstraint('points_change <> 0', name='ck_point_ledger_points_change_non_zero'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_point_ledger_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_point_ledger')),
    sa.UniqueConstraint('source_type', 'source_id', name='uq_point_ledger_source')
    )
    op.create_index('ix_point_ledger_user_created_at', 'point_ledger', ['user_id', 'created_at'], unique=False)
    op.create_table('return_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hub_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'COMPLETED', 'CANCELLED', name='return_session_status_enum'), server_default='OPEN', nullable=False),
    sa.Column('total_accepted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_rejected', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_accepted >= 0', name='ck_return_sessions_total_accepted_non_negative'),
    sa.CheckConstraint('total_points >= 0', name='ck_return_sessions_total_points_non_negative'),
    sa.CheckConstraint('total_rejected >= 0', name='ck_return_sessions_total_rejected_non_negative'),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.id'], name=op.f('fk_return_sessions_hub_id_hubs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_return_sessions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_return_sessions'))
    )
    op.create_index(op.f('ix_return_sessions_hub_id'), 'return_sessions', ['hub_id'], unique=False)
    op.create_index(op.f('ix_return_sessions_user_id'), 'return_sessions', ['user_id'], unique=False)
    op.create_table('voucher_redemptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('voucher_id', sa.UUID(), nullable=False),
    sa.Column('redemption_code', sa.String(length=80), nullable=False),
    sa.Column('points_spent', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'USED', 'EXPIRED', 'CANCELLED', name='voucher_redemption_status_enum'), server_default='ISSUED', nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expires_at IS NULL OR expires_at > created_at', name='ck_voucher_redemptions_expiration_valid'),
    sa.CheckConstraint('points_spent > 0', name='ck_voucher_redemptions_points_spent_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_voucher_redemptions_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], name=op.f('fk_voucher_redemptions_voucher_id_vouchers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voucher_redemptions')),
    sa.UniqueConstraint('redemption_code', name=op.f('uq_voucher_redemptions_redemption_code'))
    )
    op.create_index('ix_voucher_redemptions_user_created_at', 'voucher_redemptions', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_voucher_redemptions_voucher_status', 'voucher_redemptions', ['voucher_id', 'status'], unique=False)
    op.create_table('material_batches',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('hub_id', sa.UUID(), nullable=False),
    sa.Column('pickup_id', sa.UUID(), nullable=True),
    sa.Column('material_type', sa.Enum('PET', 'HDPE', 'UNKNOWN', name='material_type_enum'), nullable=False),
    sa.Column('bottle_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estimated_weight_kg', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('STORING', 'READY_FOR_PICKUP', 'PICKED_UP', 'RECEIVED', name='material_batch_status_enum'), server_default='STORING', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("material_type IN ('PET', 'HDPE')", name='ck_material_batches_supported_material'),
    sa.CheckConstraint('bottle_count >= 0', name='ck_material_batches_bottle_count_non_negative'),
    sa.CheckConstraint('estimated_weight_kg >= 0', name='ck_material_batches_weight_non_negative'),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.id'], name=op.f('fk_material_batches_hub_id_hubs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickups.id'], name=op.f('fk_material_batches_pickup_id_pickups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_batches')),
    sa.UniqueConstraint('code', name=op.f('uq_material_batches_code'))
    )
    op.create_index(op.f('ix_material_batches_hub_id'), 'material_batches', ['hub_id'], unique=False)
    op.create_index(op.f('ix_material_batches_pickup_id'), 'material_batches', ['pickup_id'], unique=False)
    op.create_table('bottle_transactions',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('material_type', sa.Enum('PET', 'HDPE', 'UNKNOWN', name='material_type_enum'), nullable=False),
    sa.Column('verified_material_type', sa.Enum('PET', 'HDPE', 'UNKNOWN', name='verified_material_type_enum'), nullable=True),
    sa.Column('status', sa.Enum('ACCEPTED', 'REJECTED', name='bottle_transaction_status_enum'), nullable=False),
    sa.Column('reject_reason', sa.Enum('WRONG_SLOT', 'BOTTLE_HAS_LIQUID', 'DIRTY_BOTTLE', 'UNSUPPORTED_MATERIAL', 'INVALID_SAMPLE_CODE', 'LOW_CONFIDENCE', 'HUB_FULL', 'UNKNOWN_ERROR', name='reject_reason_enum'), nullable=True),
    sa.Column('verification_level', sa.Enum('LEVEL_1', 'LEVEL_2', 'LEVEL_3', name='verification_level_enum'), server_default='LEVEL_1', nullable=False),
    sa.Column('cleanliness_status', sa.Enum('CLEAN', 'DIRTY', 'UNKNOWN', name='cleanliness_status_enum'), nullable=True),
    sa.Column('weight_gram', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('points_awarded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ai_confidence IS NULL OR (ai_confidence >= 0 AND ai_confidence <= 1)', name='ck_bottle_transactions_ai_confidence_valid'),
    sa.CheckConstraint('points_awarded >= 0', name='ck_bottle_transactions_points_non_negative'),
    sa.CheckConstraint('weight_gram IS NULL OR weight_gram >= 0', name='ck_bottle_transactions_weight_non_negative'),
    sa.ForeignKeyConstraint(['batch_id'], ['material_batches.id'], name=op.f('fk_bottle_transactions_batch_id_material_batches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['return_sessions.id'], name=op.f('fk_bottle_transactions_session_id_return_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bottle_transactions')),
    sa.UniqueConstraint('code', name=op.f('uq_bottle_transactions_code'))
    )
    op.create_index(op.f('ix_bottle_transactions_batch_id'), 'bottle_transactions', ['batch_id'], unique=False)
    op.create_index(op.f('ix_bottle_transactions_session_id'), 'bottle_transactions', ['session_id'], unique=False)
    op.create_table('verification_events',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('verification_level', sa.Enum('LEVEL_1', 'LEVEL_2', 'LEVEL_3', name='verification_level_enum'), nullable=False),
    sa.Column('result', sa.Enum('PASS', 'FAIL', 'REVIEW', name='verification_result_enum'), nullable=False),
    sa.Column('verifier_name', sa.String(length=80), nullable=False),
    sa.Column('verifier_version', sa.String(length=50), nullable=True),
    sa.Column('rule_code', sa.String(length=80), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_verification_events_confidence_valid'),
    sa.CheckConstraint('processing_time_ms IS NULL OR processing_time_ms >= 0', name='ck_verification_events_processing_time_non_negative'),
    sa.ForeignKeyConstraint(['transaction_id'], ['bottle_transactions.id'], name=op.f('fk_verification_events_transaction_id_bottle_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_events'))
    )
    op.create_index('ix_verification_events_transaction_created_at', 'verification_events', ['transaction_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verification_events_transaction_created_at', table_name='verification_events')
    op.drop_table('verification_events')
    op.drop_index(op.f('ix_bottle_transactions_session_id'), table_name='bottle_transactions')
    op.drop_index(op.f('ix_bottle_transactions_batch_id'), table_name='bottle_transactions')
    op.drop_table('bottle_transactions')
    op.drop_index(op.f('ix_material_batches_pickup_id'), table_name='material_batches')
    op.drop_index(op.f('ix_material_batches_hub_id'), table_name='material_batches')
    op.drop_table('material_batches')
    op.drop_index('ix_voucher_redemptions_voucher_status', table_name='voucher_redemptions')
    op.drop_index('ix_voucher_redemptions_user_created_at', table_name='voucher_redemptions')
    op.drop_table('voucher_redemptions')
    op.drop_index(op.f('ix_return_sessions_user_id'), table_name='return_sessions')
    op.drop_index(op.f('ix_return_sessions_hub_id'), table_name='return_sessions')
    op.drop_table('return_sessions')
    op.drop_index('ix_point_ledger_user_created_at', table_name='point_ledger')
    op.drop_table('point_ledger')
    op.drop_index(op.f('ix_pickups_hub_id'), table_name='pickups')
    op.drop_index(op.f('ix_pickups_driver_id'), table_name='pickups')
    op.drop_table('pickups')
    op.drop_index('ix_vouchers_status', table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_table('users')
    op.drop_table('hubs')
    op.execute("DROP TYPE IF EXISTS verification_result_enum")
    op.execute("DROP TYPE IF EXISTS cleanliness_status_enum")
    op.execute("DROP TYPE IF EXISTS verification_level_enum")
    op.execute("DROP TYPE IF EXISTS reject_reason_enum")
    op.execute("DROP TYPE IF EXISTS verified_material_type_enum")
    op.execute("DROP TYPE IF EXISTS bottle_transaction_status_enum")
    op.execute("DROP TYPE IF EXISTS material_batch_status_enum")
    op.execute("DROP TYPE IF EXISTS material_type_enum")
    op.execute("DROP TYPE IF EXISTS voucher_redemption_status_enum")
    op.execute("DROP TYPE IF EXISTS return_session_status_enum")
    op.execute("DROP TYPE IF EXISTS point_source_type_enum")
    op.execute("DROP TYPE IF EXISTS pickup_status_enum")
    op.execute("DROP TYPE IF EXISTS voucher_status_enum")
    op.execute("DROP TYPE IF EXISTS user_role_enum")
    op.execute("DROP TYPE IF EXISTS hub_status_enum")
    # ### end Alembic commands ###
